[package]
name = "xdo"
version = "0.1.0"
edition = "2021"
builder = "build.rs"
links = "xdo"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cc = "1.0.46"
libc = "0.2.122"